import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const dictionary = {
  English: {
    // Navigation / General Tabs
    home: "Home",
    features: "Features",
    opportunities: "Opportunities",
    howItWorks: "How It Works",
    contact: "Contact Us",
    signIn: "Sign In",
    getStarted: "Get Started",
    dashboard: "Dashboard",
    logout: "Log Out",
    settings: "Settings",
    saved: "Saved Items",
    notifications: "Notifications",
    tracker: "Opportunity Tracker",
    teamFinder: "Team Finder",
    activityHistory: "Activity History",
    explore: "Explore",

    // Dashboard Overview
    overview: "Overview",
    welcomeBack: "Welcome back",
    dashboardSubtitle: "Monitor your applications, upcoming events, and campus matches in real-time.",
    matchingStatus: "AI Match Score",
    pendingApplications: "Applications Tracker",
    upcomingReservations: "Reservations Tracker",
    savedItemsCount: "Saved Hub",

    // Settings Categories
    profileInfo: "Profile Info",
    passwordSecurity: "Password & Security",
    notificationsTab: "Notifications",
    privacyToggles: "Privacy & Toggles",
    themePreference: "Theme Preference",
    languageSelect: "Language Select",
    accountActions: "Account Actions",
    securityCenter: "Security Center",
    helpSupport: "Help & Support",
    aboutNearify: "About Nearify",
    activeDevices: "Active Devices",

    // Profile Settings
    editProfileInfo: "Edit Profile Info",
    fullName: "Full Name",
    emailAddress: "Email Address",
    headline: "Headline",
    organization: "Organization",
    location: "Location",
    biography: "Biography",
    linkedInHandle: "LinkedIn Handle",
    gitHubHandle: "GitHub Handle",
    portfolioWebsite: "Portfolio Website",
    saveProfileSettings: "Save Profile Settings",
    updateResume: "Update Resume",
    skills: "Skills",
    addSkill: "Add Skill",

    // Security Settings
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updatePasswordBtn: "Update Password",
    twoFactorAuth: "Two-Factor Authentication",
    twoFactorDesc: "Secure your account with 2FA codes generated by your authenticator app.",
    loginActivity: "Recent Login Activity",
    device: "Device",
    locationLabel: "Location",
    browser: "Browser",
    date: "Date",
    signOutDevice: "Sign Out Device",

    // Notifications Settings
    notificationPreferences: "Notification Preferences",
    internshipAlerts: "Internship Notifications",
    hackathonAlerts: "Hackathon Notifications",
    eventAlerts: "Event Notifications",
    foodAlerts: "Food Offer Notifications",
    emailAlerts: "Email Notifications",
    pushAlerts: "Push Notifications",
    marketingAlerts: "Marketing Notifications",

    // Privacy Settings
    privacyVisibility: "Privacy & Visibility Toggles",
    profileVisibility: "Profile Visibility",
    visibilityPublic: "Public",
    visibilityPrivate: "Private",
    visibilityConnections: "Connections Only",
    showEmail: "Show Email to Recruiters",
    showPhone: "Show Phone Number",
    showResume: "Show Resume Publicly",
    showActivity: "Show Online/Activity Status",

    // Connected Accounts
    connectedAccounts: "Connected Accounts",
    connect: "Connect",
    disconnect: "Disconnect",
    connected: "Connected",

    // Data Management
    dataManagement: "Data Management & Export",
    exportProfile: "Export Profile JSON",
    exportApplications: "Export Applications Data",
    exportReservations: "Export Reservations Data",
    exportSaved: "Export Saved Items",
    deleteAccount: "Delete Account Permanently",
    deactivateAccount: "Deactivate Account",
    
    // Theme Preferences
    themePreferences: "Theme Preferences",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemDefault: "System Default",

    // Language selector
    languagePreferences: "Language Preferences",
    appLanguage: "App Language",

    // Restaurant details & Reservation widget
    reserveTable: "Reserve a Table",
    bookingConfirmed: "Booking Confirmed",
    rescheduleReservation: "Reschedule Booking",
    cancelReservation: "Cancel Reservation",
    activeReservation: "Active Reservation",
    guestsCount: "Guests Count",
    seatingArea: "Seating Area",
    specialRequests: "Special Requests (Optional)",
    unlockVoucher: "Unlock Voucher",
    specialOffers: "Special Student Offers",
    writeReview: "Write Feedback & Review",
    submitFeedback: "Submit Feedback",

    // Help & Support
    helpCenter: "Help Center & FAQs",
    reportIssue: "Report an Issue",
    contactSupport: "Contact Support",
    feedbackForm: "Submit Feedback Form",
    feedbackSubject: "Subject",
    feedbackMessage: "Message",
    sendFeedback: "Send Feedback",

    // About Nearify
    platformVersion: "Platform Version",
    releaseNotes: "Release Notes",
    termsConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    appInfo: "Application Information",

    // Toasts & Dialogs
    successSave: "Settings saved successfully!",
    successPassword: "Password updated successfully!",
    successLanguage: "Language updated to English!",
    successCoupon: "Coupon copied to clipboard!",
    successReserve: "Table reservation confirmed!",
    successCancel: "Reservation cancelled successfully!",
    successReschedule: "Reservation rescheduled successfully!",
    loading: "Processing change...",
    confirmDelete: "Are you sure you want to permanently delete your Nearify account? All data will be lost.",
    confirmDeactivate: "Are you sure you want to deactivate your account? You can reactivate by logging back in."
  },
  Telugu: {
    // Navigation / General Tabs
    home: "హోమ్",
    features: "ఫీచర్లు",
    opportunities: "అవకాశాలు",
    howItWorks: "పనితీరు",
    contact: "సంప్రదించండి",
    signIn: "లాగిన్",
    getStarted: "ప్రారంభించండి",
    dashboard: "డాష్బోర్డ్",
    logout: "లాగ్ అవుట్",
    settings: "సెట్టింగులు",
    saved: "సేవ్ చేసినవి",
    notifications: "నోటిఫికేషన్లు",
    tracker: "అవకాశాల ట్రాకర్",
    teamFinder: "టీమ్ ఫైండర్",
    activityHistory: "చర్యల చరిత్ర",
    explore: "అన్వేషించండి",

    // Dashboard Overview
    overview: "అవలోకనం",
    welcomeBack: "స్వాగతం",
    dashboardSubtitle: "మీ దరఖాస్తులు, రాబోయే ఈవెంట్‌లు మరియు క్యాంపస్ మ్యాచ్‌లను నిజ-సమయంలో పర్యవేక్షించండి.",
    matchingStatus: "AI మ్యాచ్ స్కోర్",
    pendingApplications: "దరఖాస్తుల ట్రాకర్",
    upcomingReservations: "రిజర్వేషన్ల ట్రాకర్",
    savedItemsCount: "సేవ్ చేసిన హబ్",

    // Settings Categories
    profileInfo: "ప్రొఫైల్ సమాచారం",
    passwordSecurity: "పాస్వర్డ్ & సెక్యూరిటీ",
    notificationsTab: "నోటిఫికేషన్లు",
    privacyToggles: "ప్రైవసీ & టోగుల్స్",
    themePreference: "థీమ్ ప్రాధాన్యత",
    languageSelect: "భాష ఎంపిక",
    accountActions: "ఖాతా చర్యలు",
    securityCenter: "సెక్యూరిటీ సెంటర్",
    helpSupport: "సహాయం & మద్దతు",
    aboutNearify: "నియరిఫై గురించి",
    activeDevices: "క్రియాశీల పరికరాలు",

    // Profile Settings
    editProfileInfo: "ప్రొఫైల్ సవరణ",
    fullName: "పూర్తి పేరు",
    emailAddress: "ఇమెయిల్ చిరునామా",
    headline: "హెడ్‌లైన్",
    organization: "సంస్థ",
    location: "ప్రదేశము",
    biography: "బయోగ్రఫీ",
    linkedInHandle: "LinkedIn లింక్",
    gitHubHandle: "GitHub లింక్",
    portfolioWebsite: "పోర్ట్‌ఫోలియో వెబ్‌సైట్",
    saveProfileSettings: "ప్రొఫైల్ సేవ్ చేయి",
    updateResume: "రెజ్యూమ్ అప్‌డేట్",
    skills: "నైపుణ్యాలు",
    addSkill: "నైపుణ్యం జోడించు",

    // Security Settings
    changePassword: "పాస్‌వర్డ్ మార్చండి",
    currentPassword: "ప్రస్తుత పాస్‌వర్డ్",
    newPassword: "కొత్త పాస్‌వర్డ్",
    confirmNewPassword: "కొత్త పాస్‌వర్డ్ ధృవీకరణ",
    updatePasswordBtn: "పాస్‌వర్డ్ అప్‌డేట్ చేయి",
    twoFactorAuth: "ద్వి-కారక ధృవీకరణ (2FA)",
    twoFactorDesc: "మీ అథెంటికేటర్ యాప్ ద్వారా 2FA కోడ్‌లతో ఖాతాను మరింత సురక్షితం చేసుకోండి.",
    loginActivity: "ఇటీవలి లాగిన్ లాగ్స్",
    device: "పరికరం",
    locationLabel: "ప్రదేశం",
    browser: "బ్రౌజర్",
    date: "తేదీ",
    signOutDevice: "పరికరం నుండి సైన్ అవుట్",

    // Notifications Settings
    notificationPreferences: "నోటిఫికేషన్ ప్రాధాన్యతలు",
    internshipAlerts: "ఇంటర్న్‌షిప్ నోటిఫికేషన్లు",
    hackathonAlerts: "హాకథాన్ నోటిఫికేషన్లు",
    eventAlerts: "ఈవెంట్ నోటిఫికేషన్లు",
    foodAlerts: "ఫుడ్ ఆఫర్ నోటిఫికేషన్లు",
    emailAlerts: "ఇమెయిల్ నోటిఫికేషన్లు",
    pushAlerts: "పుష్ నోటిఫికేషన్లు",
    marketingAlerts: "మార్కెటింగ్ నోటిఫికేషన్లు",

    // Privacy Settings
    privacyVisibility: "ప్రైవసీ & విజిబిలిటీ టోగుల్స్",
    profileVisibility: "ప్రొఫైల్ విజిబిలిటీ",
    visibilityPublic: "పబ్లిక్",
    visibilityPrivate: "ప్రైవేట్",
    visibilityConnections: "కనెక్షన్స్ మాత్రమే",
    showEmail: "రిక్రూటర్లకు ఇమెయిల్ చూపించు",
    showPhone: "ఫోన్ నంబర్ చూపించు",
    showResume: "రెజ్యూమ్ బహిరంగంగా చూపించు",
    showActivity: "ఆన్‌లైన్ స్థితిని చూపించు",

    // Connected Accounts
    connectedAccounts: "కనెక్ట్ చేయబడిన ఖాతాలు",
    connect: "కనెక్ట్ చేయి",
    disconnect: "డిస్‌కనెక్ట్ చేయి",
    connected: "కనెక్ట్ చేయబడింది",

    // Data Management
    dataManagement: "డేటా నిర్వహణ & ఎగుమతి",
    exportProfile: "ప్రొఫైల్ JSON ఎగుమతి",
    exportApplications: "దరఖాస్తుల డేటా ఎగుమతి",
    exportReservations: "రిజర్వేషన్ల డేటా ఎగుమతి",
    exportSaved: "సేవ్ చేసిన వాటి ఎగుమతి",
    deleteAccount: "ఖాతాను శాశ్వతంగా తొలగించు",
    deactivateAccount: "ఖాతాను నిష్క్రియం చేయి",

    // Theme Preferences
    themePreferences: "థీమ్ ప్రాధాన్యతలు",
    lightMode: "లైట్ మోడ్",
    darkMode: "డార్క్ మోడ్",
    systemDefault: "సిస్టమ్ డిఫాల్ట్",

    // Language selector
    languagePreferences: "భాష ప్రాధాన్యతలు",
    appLanguage: "యాప్ భాష",

    // Restaurant details & Reservation widget
    reserveTable: "టేబుల్ రిజర్వ్ చేయండి",
    bookingConfirmed: "బుకింగ్ ఖరారైంది",
    rescheduleReservation: "బుకింగ్ వాయిదా వేయి",
    cancelReservation: "రిజర్వేషన్ రద్దు చేయి",
    activeReservation: "క్రియాశీల రిజర్వేషన్",
    guestsCount: "అతిథుల సంఖ్య",
    seatingArea: "కూర్చునే స్థలం",
    specialRequests: "ప్రత్యేక అభ్యర్థనలు (ఐచ్ఛికం)",
    unlockVoucher: "వోచర్ అన్‌లాక్ చేయి",
    specialOffers: "ప్రత్యేక విద్యార్థి ఆఫర్లు",
    writeReview: "అభిప్రాయాలు & సమీక్షలు",
    submitFeedback: "సమీక్ష సమర్పించు",

    // Help & Support
    helpCenter: "సహాయ కేంద్రం & ప్రశ్నలు",
    reportIssue: "సమస్యను నివేదించండి",
    contactSupport: "సహాయక బృందాన్ని సంప్రదించండి",
    feedbackForm: "అభిప్రాయ ఫారమ్",
    feedbackSubject: "విషయం",
    feedbackMessage: "సందేశం",
    sendFeedback: "అభిప్రాయాన్ని పంపండి",

    // About Nearify
    platformVersion: "ప్లాట్‌ఫారమ్ వెర్షన్",
    releaseNotes: "విడుదల గమనికలు",
    termsConditions: "నిబంధనలు & షరతులు",
    privacyPolicy: "గోపनीयత విధానం",
    appInfo: "అప్లికేషన్ సమాచారం",

    // Toasts & Dialogs
    successSave: "సెట్టింగులు విజయవంతంగా సేవ్ చేయబడ్డాయి!",
    successPassword: "పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది!",
    successLanguage: "భాష తెలుగులోకి మార్చబడింది!",
    successCoupon: "కూపన్ క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది!",
    successReserve: "టేబుల్ రిజర్వేషన్ ఖరారైంది!",
    successCancel: "రిజర్వేషన్ విజయవంతంగా రద్దు చేయబడింది!",
    successReschedule: "రిజర్వేషన్ విజయవంతంగా వాయిదా వేయబడింది!",
    loading: "ప్రక్రియ కొనసాగుతోంది...",
    confirmDelete: "మీరు మీ నియరిఫై ఖాతాను శాశ్వతంగా తొలగించాలనుకుంటున్నారా? మొత్తం డేటా పోతుంది.",
    confirmDeactivate: "మీరు మీ ఖాతాను నిష్క్రియం చేయాలనుకుంటున్నారా? లాగిన్ చేయడం ద్వారా తిరిగి సక్రియం చేయవచ్చు."
  },
  Hindi: {
    // Navigation / General Tabs
    home: "होम",
    features: "विशेषताएं",
    opportunities: "अवसर",
    howItWorks: "कार्यप्रणाली",
    contact: "संपर्क करें",
    signIn: "साइन इन",
    getStarted: "शुरू करें",
    dashboard: "डैशबोर्ड",
    logout: "लॉग आउट",
    settings: "सेटिंग्स",
    saved: "सहेजे गए",
    notifications: "सूचनाएं",
    tracker: "अवसर ट्रैकर",
    teamFinder: "टीम खोजक",
    activityHistory: "गतिविधि इतिहास",
    explore: "अन्वेषण करें",

    // Dashboard Overview
    overview: "अवलोकन",
    welcomeBack: "स्वागत हे",
    dashboardSubtitle: "वास्तविक समय में अपने आवेदनों, आगामी कार्यक्रमों और परिसर के मैचों की निगरानी करें।",
    matchingStatus: "AI मैच स्कोर",
    pendingApplications: "आवेदन ट्रैकर",
    upcomingReservations: "आरक्षण ट्रैकर",
    savedItemsCount: "सहेजा गया हब",

    // Settings Categories
    profileInfo: "प्रोफ़ाइल जानकारी",
    passwordSecurity: "पासवर्ड और सुरक्षा",
    notificationsTab: "सूचनाएं",
    privacyToggles: "गोपनीयता और टॉगल",
    themePreference: "थीम प्राथमिकता",
    languageSelect: "भाषा चयन",
    accountActions: "खाता कार्रवाइयाँ",
    securityCenter: "सुरक्षा केंद्र",
    helpSupport: "सहायता और समर्थन",
    aboutNearify: "नियरीफ़ाई के बारे में",
    activeDevices: "सक्रिय उपकरण",

    // Profile Settings
    editProfileInfo: "प्रोफ़ाइल संपादित करें",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    headline: "हेडलाइन",
    organization: "संगठन",
    location: "स्थान",
    biography: "जीवनी",
    linkedInHandle: "LinkedIn लिंक",
    gitHubHandle: "GitHub लिंक",
    portfolioWebsite: "पोर्टफोलियो वेबसाइट",
    saveProfileSettings: "प्रोफ़ाइल सहेजें",
    updateResume: "रिज्यूमे अपडेट करें",
    skills: "कौशल",
    addSkill: "कौशल जोड़ें",

    // Security Settings
    changePassword: "पासवर्ड बदलें",
    currentPassword: "वर्तमान पासवर्ड",
    newPassword: "नया पासवर्ड",
    confirmNewPassword: "नए पासवर्ड की पुष्टि",
    updatePasswordBtn: "पासवर्ड अपडेट करें",
    twoFactorAuth: "द्वि-कारक प्रमाणीकरण (2FA)",
    twoFactorDesc: "अपने प्रमाणक ऐप द्वारा जनरेट किए गए 2FA कोड के साथ अपने खाते को सुरक्षित करें।",
    loginActivity: "हाल की लॉगिन गतिविधि",
    device: "उपकरण",
    locationLabel: "स्थान",
    browser: "ब्राउज़र",
    date: "तारीख",
    signOutDevice: "उपकरण से साइन आउट",

    // Notifications Settings
    notificationPreferences: "अधिसूचना प्राथमिकताएं",
    internshipAlerts: "इंटरर्नशिप सूचनाएं",
    hackathonAlerts: "हैकाथॉन सूचनाएं",
    eventAlerts: "कार्यक्रम सूचनाएं",
    foodAlerts: "खाद्य ऑफ़र सूचनाएं",
    emailAlerts: "ईमेल सूचनाएं",
    pushAlerts: "पुश सूचनाएं",
    marketingAlerts: "मार्केटिंग सूचनाएं",

    // Privacy Settings
    privacyVisibility: "गोपनीयता और दृश्यता टॉगल",
    profileVisibility: "प्रोफ़ाइल दृश्यता",
    visibilityPublic: "सार्वजनिक",
    visibilityPrivate: "निजी",
    visibilityConnections: "केवल कनेक्शन",
    showEmail: "नियोक्ताओं को ईमेल दिखाएं",
    showPhone: "फ़ोन नंबर दिखाएं",
    showResume: "रिज्यूमे सार्वजनिक रूप से दिखाएं",
    showActivity: "ऑनलाइन गतिविधि स्थिति दिखाएं",

    // Connected Accounts
    connectedAccounts: "संबद्ध खाते",
    connect: "कनेक्ट करें",
    disconnect: "डिस्कनेक्ट करें",
    connected: "कनेक्टेड",

    // Data Management
    dataManagement: "डेटा प्रबंधन और निर्यात",
    exportProfile: "प्रोफ़ाइल JSON निर्यात",
    exportApplications: "आवेदन डेटा निर्यात",
    exportReservations: "आरक्षण डेटा निर्यात",
    exportSaved: "सहेजे गए आइटम निर्यात",
    deleteAccount: "खाता स्थायी रूप से हटाएं",
    deactivateAccount: "खाता निष्क्रिय करें",

    // Theme Preferences
    themePreferences: "थीम प्राथमिकताएं",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemDefault: "सिस्टम डिफ़ॉल्ट",

    // Language selector
    languagePreferences: "भाषा प्राथमिकताएं",
    appLanguage: "ऐप की भाषा",

    // Restaurant details & Reservation widget
    reserveTable: "टेबल बुक करें",
    bookingConfirmed: "बुकिंग की पुष्टि",
    rescheduleReservation: "आरक्षण पुनर्निर्धारित करें",
    cancelReservation: "आरक्षण रद्द करें",
    activeReservation: "सक्रिय आरक्षण",
    guestsCount: "अतिथियों की संख्या",
    seatingArea: "बैठने का क्षेत्र",
    specialRequests: "विशेष अनुरोध (वैकल्पिक)",
    unlockVoucher: "वाउचर अनलॉक करें",
    specialOffers: "विशेष छात्र ऑफ़र",
    writeReview: "प्रतिक्रिया और समीक्षा",
    submitFeedback: "समीक्षा जमा करें",

    // Help & Support
    helpCenter: "सहायता केंद्र और अक्सर पूछे जाने वाले प्रश्न",
    reportIssue: "समस्या की रिपोर्ट करें",
    contactSupport: "सहायता टीम से संपर्क करें",
    feedbackForm: "प्रतिक्रिया फॉर्म",
    feedbackSubject: "विषय",
    feedbackMessage: "संदेश",
    sendFeedback: "प्रतिक्रिया भेजें",

    // About Nearify
    platformVersion: "प्लेटफ़ॉर्म संस्करण",
    releaseNotes: "रिलीज़ नोट्स",
    termsConditions: "नियम और शर्तें",
    privacyPolicy: "गोपनीयता नीति",
    appInfo: "एप्लिकेशन की जानकारी",

    // Toasts & Dialogs
    successSave: "सेटिंग्स सफलतापूर्वक सहेजी गईं!",
    successPassword: "पासवर्ड सफलतापूर्वक अपडेट किया गया!",
    successLanguage: "भाषा बदलकर हिंदी कर दी गई है!",
    successCoupon: "कूपन क्लिपबोर्ड पर कॉपी हो गया!",
    successReserve: "टेबल आरक्षण की पुष्टि हो गई!",
    successCancel: "आरक्षण सफलतापूर्वक रद्द कर दिया गया!",
    successReschedule: "आरक्षण सफलतापूर्वक पुनर्निर्धारित किया गया!",
    loading: "प्रक्रिया जारी है...",
    confirmDelete: "क्या आप वाकई अपना नियरीफ़ाई खाता स्थायी रूप से हटाना चाहते हैं? सभी डेटा खो जाएगा।",
    confirmDeactivate: "क्या आप वाकई अपना खाता निष्क्रिय करना चाहते हैं? लॉगिन करके इसे फिर से सक्रिय किया जा सकता है।"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('nearify_language') || 'English';
  });

  const setLanguage = (lang) => {
    if (dictionary[lang]) {
      setLanguageState(lang);
      localStorage.setItem('nearify_language', lang);
    }
  };

  const t = (key, defaultValue = '') => {
    const langDict = dictionary[language] || dictionary.English;
    return langDict[key] || defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: Object.keys(dictionary) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
